version: "3"

services:
    express:
        image: mongo-express
        container_name: express
        restart: always
        ports:
            - 8027:8081
        environment:
            ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_DB_USER:-root}:${MONGO_DB_PASSWORD-password}@mongo:27017/"
            ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_DB_USER:-root}"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_DB_PASSWORD:-password}"
        networks:
            - processton