version: "3"

services:
    mailpit:
        image: "axllent/mailpit:latest"
        container_name: mailpit
        ports:
            - "3025:1025"
            - "8025:8025"
        networks:
            - processton