version: "3"

services:
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "3026:9000"
            - "8024:9001"
        volumes:
            - ../storage/minio/data:/data
        environment:
            MINIO_ROOT_USER: masoud
            MINIO_ROOT_PASSWORD: Strong#Pass#2022
        command: server --console-address ":9001" /data