version: "3"

services:
    mongo:
        image: mongo
        restart: always
        container_name: mongodb
        hostname: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USER:-root}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD:-password}"
            MONGO_INITDB_DATABASE: "${MONGO_DB_DATABASE:-project}"
        volumes:
            - ../data/mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ../data/mongo/db:/data/db
        networks:
            - processton